import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/">🏠</Link> 
        <Link href="/login">Login</Link> 
        <Link href="/register">회원가입</Link> 
        <Link href="/post">게시물</Link> 
        {children}</body>
    </html>
  )
}
